"""add day index to firm characteristics

Revision ID: 07557ece05f7
Revises: 7146a0bdcf85
Create Date: 2026-08-27 01:01:46.938487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07557ece05f7'
down_revision: Union[str, Sequence[str], None] = '7146a0bdcf85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_firm_characteristics_day'), 'firm_characteristics', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_characteristics_day'), table_name='firm_characteristics')
    # ### end Alembic commands ###
