"""Add firm_characteristics table

Revision ID: 7146a0bdcf85
Revises: e9f027e54bd2
Create Date: 2026-08-25 23:58:21.173499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7146a0bdcf85'
down_revision: Union[str, Sequence[str], None] = 'e9f027e54bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_characteristics',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['universe_stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firm_characteristics')
    # ### end Alembic commands ###
