"""add margin_locked to positions

Revision ID: cbf2d19fc4fe
Revises: 07557ece05f7
Create Date: 2026-09-24 16:35:02.052566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbf2d19fc4fe'
down_revision: Union[str, Sequence[str], None] = '07557ece05f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('portfolio_snapshots_user_id_fkey'), 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('portfolios_user_id_fkey'), 'portfolios', type_='foreignkey')
    op.drop_constraint(op.f('positions_user_id_fkey'), 'positions', type_='foreignkey')
    op.alter_column('user_preferences', 'theme',
               existing_type=postgresql.ENUM('Light', 'Dark', name='Theme'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('\'Dark\'::"Theme"'))
    op.drop_constraint(op.f('user_preferences_user_id_fkey'), 'user_preferences', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_preferences_user_id_fkey'), 'user_preferences', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('user_preferences', 'theme',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Light', 'Dark', name='Theme'),
               existing_nullable=False,
               existing_server_default=sa.text('\'Dark\'::"Theme"'))
    op.create_foreign_key(op.f('positions_user_id_fkey'), 'positions', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('portfolios_user_id_fkey'), 'portfolios', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('portfolio_snapshots_user_id_fkey'), 'portfolio_snapshots', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
