"""initial schema

Revision ID: e9f027e54bd2
Revises: 
Create Date: 2026-08-24 23:51:19.886425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f027e54bd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_predictions',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('k_factors', sa.Integer(), nullable=False),
    sa.Column('weight_for_symbols', sa.ARRAY(sa.Numeric()), nullable=False),
    sa.PrimaryKeyConstraint('model_name', 'as_of_date')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=False),
    sa.Column('daily_return', sa.Numeric(), nullable=False),
    sa.Column('cumulative_return', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('day', 'user_id')
    )
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('universe_stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('auto_trade', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['universe_stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'user_id')
    )
    op.create_table('positions',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['universe_stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'user_id')
    )
    op.create_table('price_history',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['universe_stocks.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('user_preferences')
    op.drop_table('universe_stocks')
    op.drop_table('portfolios')
    op.drop_table('portfolio_snapshots')
    op.drop_table('model_predictions')
    # ### end Alembic commands ###
